name: firebase_otp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  device_info: 
  flutter_phoenix:
  firebase_auth: null
  firebase_core: null
  pin_entry_text_field: ^0.1.4
  shared_preferences: null

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
